# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180223_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
