# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180228_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('\u043d\u043e\u0432\u044b\u0439', '\u041d\u043e\u0432\u044b\u0439'), ('\u043e\u0442\u043c\u0435\u043d\u0430', '\u041e\u0442\u043c\u0435\u043d\u0435\u043d'), ('\u0432\u044b\u043f\u043e\u043b\u043d\u0435\u043d', '\u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d')], max_length=64),
        ),
    ]
